[workspace]
resolver = "2"
members = [
  "src/backend",
  "src/web",
]

[workspace.dependencies]
futures = "0.3"
anyhow = "1.0"
thiserror = "1.0"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
serde = "1.0"
serde_json = "1.0"
tracing-subscriber = "0.3.8"
tracing = "0.1.40"