FROM clux/muslrust AS builder

RUN ln -s /bin/g++ /bin/musl-g++
RUN apt-get update && apt-get install -y build-essential \
    curl \
    openssl libssl-dev \
    libsasl2-2 libsasl2-dev libsasl2-modules \
    ca-certificates \
    pkg-config \
    valgrind \
    zlib1g-dev

COPY . .

RUN cargo build --release --package loyalty-backend \
    && strip --strip-debug target/*/release/loyalty-backend \
    && cp target/*/release/loyalty-backend /usr/local/bin/

ENTRYPOINT ["/usr/local/bin/loyalty-backend"]

# FROM alpine AS final
# RUN apk --no-cache add ca-certificates \
#   && update-ca-certificates
# COPY --from=builder /usr/local/bin/loyalty-backend /usr/local/bin
# ENTRYPOINT ["/usr/local/bin/loyalty-backend"]