FROM rust:alpine as builder

ENV RUSTFLAGS="-C target-feature=-crt-static"
RUN apk add pkgconfig openssl-dev libc-dev musl-dev bash alpine-sdk
COPY . .
COPY Cargo.toml Cargo.toml

RUN cargo build --release --package loyalty-backend
RUN strip target/release/loyalty-backend

FROM alpine:latest
RUN apk update \
    && apk add openssl ca-certificates libgcc

EXPOSE 8080

COPY --from=builder /target/release/loyalty-backend .

ENTRYPOINT ["/loyalty-backend"]