FROM rust:alpine as builder

RUN apk add pkgconfig openssl-dev libc-dev musl-dev
COPY . .
COPY Cargo.toml Cargo.toml
RUN cargo build --release --package loyalty-web
RUN strip target/release/loyalty-web

FROM alpine:latest
RUN apk update \
    && apk add openssl ca-certificates libgcc

EXPOSE 8080

COPY --from=builder /target/release/loyalty-web .

ENTRYPOINT ["/loyalty-web"]