FROM --platform=${BUILDPLATFORM} rust:alpine as builder

ARG TARGETPLATFORM

ENV RUSTFLAGS="-C target-feature=-crt-static"
RUN apk update && apk add pkgconfig openssl-dev libc-dev musl-dev bash alpine-sdk

COPY ./scripts ./scripts

# The leading '.' passes the environment variable back up to Docker build
RUN . ./scripts/target.sh rustup target add $RUST_TARGET

ENV CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_LINKER=aarch64-linux-gnu-gcc   
ENV CARGO_TARGET_X86_64_UNKNOWN_LINUX_GNU_LINKER=x86_64-linux-gnu-gcc

COPY . .
COPY Cargo.toml Cargo.toml

RUN cargo build --release --package loyalty-web
RUN strip target/release/loyalty-web

FROM alpine:latest
RUN apk update \
    && apk add openssl ca-certificates libgcc

EXPOSE 8080

COPY --from=builder /target/release/loyalty-web .

ENTRYPOINT ["/loyalty-web"]
