app = "loyalty-web"

kill_signal = "SIGINT"
kill_timeout = 5

[build]
dockerfile = "Dockerfile-web"

[[services]]
internal_port = 8080
protocol = "tcp"

[[services.ports]]
handlers = ["tls", "http"]
port = "443"

[env]
SERVICE_NAME = "loyalty-web-fly"
