app = "loyalty-simulator"

[build]
dockerfile = "Dockerfile-simulator"

kill_signal = "SIGINT"
kill_timeout = 5

[env]
SERVICE_NAME = "loyalty-simulator-fly"
LAMBDA_API_ENDPOINT = "https://loyalty-web.fly.dev"
