AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  Env: 
    Type: String
    Default: dev
  CommitHash:
    Type: String
    Default: latest
  DDApiKeySecretArn:
    Type: String
  DDSite:
    Type: String
  DatabaseUrl:
    Type: String
  ConfluentCloudCredentialsArn:
    Type: String
  KafkaBootstrapServers:
    Type: String
  MomentoApiKey:
    Type: String
  CacheName:
    Type: String

Globals:
  Function:
    MemorySize: 256
    Handler: bootstrap
    Runtime: provided.al2023
    CodeUri: .
    Architectures:
      - arm64
    Environment:
      Variables:
        DATABASE_URL: !Ref DatabaseUrl
        ENV: !Ref Env
        DD_ENV: !Ref Env
        DD_API_KEY_SECRET_ARN: !Ref DDApiKeySecretArn
        DD_SITE: !Ref DDSite
        DD_VERSION: !Ref CommitHash
        DD_EXTENSION_VERSION: "next"
        RUST_LOG: "info"
        MOMENTO_API_KEY: !Ref MomentoApiKey
        CACHE_NAME: !Ref CacheName

Resources:
  LoyaltyBackend:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: rust-cargolambda
      BuildProperties:
        Binary: loyalty-backend-lambda
    Properties:
      FunctionName: loyalty-backend
      Environment:
        Variables:
          DD_SERVICE: loyalty-backend-lambda
          SERVICE_NAME: loyalty-backend-lambda
      Timeout: 60
      Layers:
        - !Sub arn:aws:lambda:${AWS::Region}:464622532012:layer:Datadog-Extension-ARM:65
      Policies:
        - AWSSecretsManagerGetSecretValuePolicy:
            SecretArn: !Ref ConfluentCloudCredentialsArn
        - AWSSecretsManagerGetSecretValuePolicy:
            SecretArn: !Ref DDApiKeySecretArn
        - SQSSendMessagePolicy:
            QueueName: !GetAtt OrderCompletedKafkaDLQ.QueueName
      Events:
        KafkaOrderCompletedEvent:
          Type: SelfManagedKafka
          Properties:
            BatchSize: 10
            Enabled: true
            ConsumerGroupId: loyalty-lambda
            DestinationConfig:
              OnFailure:
                Destination: !GetAtt OrderCompletedKafkaDLQ.Arn
            KafkaBootstrapServers:
              - !Ref KafkaBootstrapServers
            SourceAccessConfigurations: 
              - Type: BASIC_AUTH
                URI: !Ref ConfluentCloudCredentialsArn
            Topics:
              - order-completed

  LoyaltyApi:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: rust-cargolambda
      BuildProperties:
        Binary: loyalty-web
    Properties:
      FunctionName: loyalty-web
      Environment:
        Variables:
          DD_SERVICE: loyalty-web-lambda
          SERVICE_NAME: loyalty-web-lambda
      Timeout: 3
      Policies:
        - AWSSecretsManagerGetSecretValuePolicy:
            SecretArn: !Ref DDApiKeySecretArn
      FunctionUrlConfig:
        AuthType:  NONE
        InvokeMode: BUFFERED
      Layers:
        - !Sub arn:aws:lambda:${AWS::Region}:753240598075:layer:LambdaAdapterLayerArm64:23
        - !Sub arn:aws:lambda:${AWS::Region}:464622532012:layer:Datadog-Extension-ARM:65

  OrderCompletedKafkaDLQ:
      Type: AWS::SQS::Queue