[package]
name = "rust-kafka-backend"
version = "0.1.0"
edition = "2021"

[dependencies]
futures = {workspace = true}
serde_json = {workspace = true}
tokio = {workspace = true}
tracing = {workspace = true}
tracing-subscriber = {workspace = true}
serde = { version = "1.0.210", features = ["derive"] }
clap = "2.18.0"

[dependencies.rdkafka]
version     = "~0.36"
features    = ["ssl", "sasl"]