name: Build Simulator

on:
  workflow_dispatch:
  push:
    paths:
      - "src/simulator/**"
      - "Dockerfile-simulator"
      - ".github/workflows/build-simulator.yaml"

permissions:
  id-token: write
  contents: read

jobs:
  package-simulator:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Declare some variables
        shell: bash
        run: |
          echo "sha_short=$(git rev-parse --short "$GITHUB_SHA")" >> "$GITHUB_ENV"
      - name: Build & Push Simulator
        uses: docker/build-push-action@v6
        with:
          file: Dockerfile-simulator
          push: true
          tags: plantpowerjames/modern-apps-loyalty-simulator:${{env.sha_short}},plantpowerjames/modern-apps-loyalty-simulator:latest
          platforms: linux/amd64