name: ci

on:
  push:
    paths: 
      - 'src/**'
      - 'Dockerfile-web'
      - 'Dockerfile-backend'
      - '.github/workflows/ci.yaml'

permissions:
  id-token: write
  contents: read
    
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Run core library tests
        shell: bash
        run: |
          cargo test --package loyalty_core
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Declare some variables
        shell: bash
        run: |
          echo "sha_short=$(git rev-parse --short "$GITHUB_SHA")" >> "$GITHUB_ENV"
      -
        name: Build and push web
        uses: docker/build-push-action@v6
        with:
          file: Dockerfile-web
          push: true
          tags: plantpowerjames/modern-apps-loyalty-web:${{env.sha_short}}
          platforms: linux/amd64
      -
        name: Build and push backend
        uses: docker/build-push-action@v6
        with:
          file: Dockerfile-backend
          push: true
          tags: plantpowerjames/modern-apps-loyalty-backend:${{env.sha_short}}
          platforms: linux/amd64