name: ci

on:
  workflow_dispatch:
  push:
    paths:
      - "src/**"
      - "Dockerfile-web"
      - "Dockerfile-backend"
      - ".github/workflows/ci.yaml"

permissions:
  id-token: write
  contents: read

jobs:
  # test:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v4
  #     - name: Install Rust
  #       uses: actions-rs/toolchain@v1
  #       with:
  #         toolchain: stable
  #     - name: Run core library tests
  #       shell: bash
  #       run: |
  #         cargo test --package loyalty_core

  # package-web:
  #   runs-on: ubuntu-latest
  #   needs: test
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v4
  #     - name: Set up QEMU
  #       uses: docker/setup-qemu-action@v3
  #     - name: Set up Docker Buildx
  #       uses: docker/setup-buildx-action@v3
  #     - name: Login to Docker Hub
  #       uses: docker/login-action@v3
  #       with:
  #         username: ${{ secrets.DOCKERHUB_USERNAME }}
  #         password: ${{ secrets.DOCKERHUB_TOKEN }}
  #     - name: Declare some variables
  #       shell: bash
  #       run: |
  #         echo "sha_short=$(git rev-parse --short "$GITHUB_SHA")" >> "$GITHUB_ENV"
  #     - name: Build and push web
  #       uses: docker/build-push-action@v6
  #       with:
  #         file: Dockerfile-web
  #         push: true
  #         tags: plantpowerjames/modern-apps-loyalty-web:${{env.sha_short}}
  #         platforms: linux/amd64

  # package-backend:
  #   runs-on: ubuntu-latest
  #   needs: test
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v4
  #     - name: Set up QEMU
  #       uses: docker/setup-qemu-action@v3
  #     - name: Set up Docker Buildx
  #       uses: docker/setup-buildx-action@v3
  #     - name: Login to Docker Hub
  #       uses: docker/login-action@v3
  #       with:
  #         username: ${{ secrets.DOCKERHUB_USERNAME }}
  #         password: ${{ secrets.DOCKERHUB_TOKEN }}
  #     - name: Declare some variables
  #       shell: bash
  #       run: |
  #         echo "sha_short=$(git rev-parse --short "$GITHUB_SHA")" >> "$GITHUB_ENV"
  #     - name: Build and push web
  #       uses: docker/build-push-action@v6
  #       with:
  #         file: Dockerfile-backend
  #         push: true
  #         tags: plantpowerjames/modern-apps-loyalty-backend:${{env.sha_short}}
  #         platforms: linux/amd64

  integration-test:
    runs-on: ubuntu-latest
    # needs:
    #   - package-web
    #   - package-backend
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Install sqlx from crates.io
        uses: baptiste0928/cargo-install@v3
        with:
          crate: sqlx-cli
          version: '^0.8' # You can specify any semver range
      - name: Run integration tests
        shell: bash
        working-directory: .
        run: |
          make integration-test-ci
